<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Blog.master" CodeBehind="BlogPostTemplate.aspx.vb" Inherits="CarolinesBlog.WebForm1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="/app/css/BlogPostTemplate.css" rel="stylesheet" type="text/css" />
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="BlogContent" runat="server">
    <div id="blog_content">
        <h1 class="blog-post-header">My 6-Year Hair Growth Journey & What I Learned</h1>
        <div class="blog-post-date"><span>December 2, 2020</span></div>
        <img class="blog-post-picture" src="app/Images/DSCN0002.JPG" width="100%" height: "auto";/>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque sodales ut etiam sit. Quam elementum pulvinar etiam non. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Viverra suspendisse potenti nullam ac tortor vitae purus. Ac auctor augue mauris augue neque gravida. Suscipit tellus mauris a diam maecenas. Velit laoreet id donec ultrices tincidunt arcu. Purus non enim praesent elementum. Egestas sed sed risus pretium quam vulputate. Cum sociis natoque penatibus et magnis. Habitasse platea dictumst vestibulum rhoncus. Non pulvinar neque laoreet suspendisse interdum consectetur libero id. Nec nam aliquam sem et.

Quam viverra orci sagittis eu volutpat odio. Tincidunt eget nullam non nisi est sit amet facilisis magna. Sed felis eget velit aliquet sagittis id consectetur purus ut. Sed augue lacus viverra vitae congue eu consequat. Arcu dictum varius duis at consectetur. Sapien faucibus et molestie ac feugiat sed. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Vivamus at augue eget arcu dictum. Cursus turpis massa tincidunt dui ut ornare lectus. Nec tincidunt praesent semper feugiat nibh sed. At varius vel pharetra vel.

Eu sem integer vitae justo. Nibh mauris cursus mattis molestie. Tincidunt id aliquet risus feugiat in ante metus dictum at. Ut venenatis tellus in metus vulputate eu scelerisque felis. Tortor posuere ac ut consequat. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. Arcu dui vivamus arcu felis bibendum. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Penatibus et magnis dis parturient montes. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Justo eget magna fermentum iaculis eu non diam phasellus. Lacus vel facilisis volutpat est velit egestas dui id ornare. Odio ut sem nulla pharetra diam. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Sollicitudin tempor id eu nisl nunc mi ipsum. In massa tempor nec feugiat nisl pretium fusce. Ut morbi tincidunt augue interdum velit euismod in. Ultricies mi eget mauris pharetra et ultrices neque ornare aenean.

Proin nibh nisl condimentum id venenatis a. Lacus vestibulum sed arcu non odio euismod lacinia. Tincidunt lobortis feugiat vivamus at augue. Pharetra magna ac placerat vestibulum. Donec et odio pellentesque diam volutpat commodo sed. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Vitae ultricies leo integer malesuada nunc vel risus. In tellus integer feugiat scelerisque varius. Ac turpis egestas integer eget aliquet nibh praesent tristique. Pellentesque habitant morbi tristique senectus et. Pharetra sit amet aliquam id diam maecenas ultricies mi. Tristique sollicitudin nibh sit amet commodo.

Ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Venenatis cras sed felis eget velit aliquet sagittis id. Lectus mauris ultrices eros in cursus turpis massa. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Purus in massa tempor nec feugiat. Amet dictum sit amet justo. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Vulputate eu scelerisque felis imperdiet proin. At elementum eu facilisis sed odio morbi quis commodo odio. Eget aliquet nibh praesent tristique magna sit amet purus gravida. Dapibus ultrices in iaculis nunc. Sapien eget mi proin sed libero enim. Sed euismod nisi porta lorem. Quis vel eros donec ac odio tempor orci. Ut sem nulla pharetra diam. Morbi tincidunt augue interdum velit euismod in. Lorem ipsum dolor sit amet consectetur adipiscing. Pellentesque adipiscing commodo elit at. Dignissim cras tincidunt lobortis feugiat vivamus at.</p>
    </div>
</asp:Content>
